# Generated by Django 4.2 on 2023-04-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_project.payment')),
                ('bankAccount', models.CharField(max_length=200, null=True)),
            ],
            bases=('web_project.payment',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_project.product')),
                ('type', models.CharField(choices=[('Orange Juice', 'Orange Juice'), ('Apple Juice', 'Apple Juice'), ('Grapefruit Juice', 'Grapefruit Juice'), ('Black tea', 'Black tea')], max_length=200, null=True)),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE')], max_length=200, null=True)),
            ],
            bases=('web_project.product',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_project.product')),
                ('type', models.CharField(choices=[('B', 'BREAKFAST'), ('L', 'LUNCH'), ('D', 'DINNER')], max_length=200, null=True)),
            ],
            bases=('web_project.product',),
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_project.product')),
                ('type', models.CharField(choices=[('A', 'APPLE'), ('B', 'BANANA'), ('P', 'PEAR')], max_length=200, null=True)),
            ],
            bases=('web_project.product',),
        ),
        migrations.CreateModel(
            name='MobilePay',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_project.payment')),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
            ],
            bases=('web_project.payment',),
        ),
    ]
