# Generated by Django 4.2 on 2023-04-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0003_order_payment_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='web_project.product'),
        ),
    ]
