# Generated by Django 4.2 on 2023-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0004_order_date_created_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Juice', 'Juice')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='type',
            field=models.CharField(default='Fruit', max_length=200, null=True),
        ),
    ]
