# Generated by Django 4.2 on 2023-05-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0005_alter_drink_type_alter_fruit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='size',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='type',
        ),
        migrations.RemoveField(
            model_name='food',
            name='type',
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='type',
        ),
        migrations.AddField(
            model_name='food',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fruit',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
